# Generated by Django 5.2.6 on 2025-09-18 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10)),
                ('email', models.EmailField(default='johdoe@exmaple.com', max_length=254)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
